apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-vacation-deployment
  namespace: default
  labels:
    app.kubernetes.io/component: ms-vacation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ms-vacation
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ms-vacation
    spec:
      containers:
        - env:
            - name: MS_VACATION_URL
              valueFrom:
                secretKeyRef:
                  key: MS_VACATION_URL
                  name: ms.auth.secrets
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USERNAME
                  name: ms.auth.secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: ms.auth.secrets
            - name: MS_VACATION_PORT
              valueFrom:
                secretKeyRef:
                  key: MS_VACATION_PORT
                  name: ms.auth.secrets
            - name: CLINET_MS_USER_URL
              valueFrom:
                secretKeyRef:
                  key: CLINET_MS_USER_URL
                  name: ms.auth.secrets
            - name: CLIENT_MS_MINIO_URL
              valueFrom:
                secretKeyRef:
                  key: CLIENT_MS_MINIO_URL
                  name: ms.auth.secrets
            - name: CLIENT_MS_PERMISSION_URL
              valueFrom:
                secretKeyRef:
                  key: CLIENT_MS_PERMISSION_URL
                  name: ms.auth.secrets
          name: ms-vacation
          image: yunuskazimov94/ms-vacation
          ports:
            - name: http
              containerPort: 8044
              protocol: TCP