apiVersion: v1
kind: Service
metadata:
  name: ms-vacation-loadbalancer
  labels:
    app.kubernetes.io/component: ms-vacation
spec:
#  type: NodePort
  ports:
    - port: 80
      targetPort: 8044
  selector:
      app.kubernetes.io/component: ms-vacation